KnowledgeTestingApplication/KnowledgeTestingApplication/Controllers/TestController.cs
using AutoMapper;
using KnowledgeTestingApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KnowledgeTestingApplication.Controllers
{
    public class TestController : Controller
    {
        // GET: Test
        [Authorize]
        public ActionResult Index(int page = 1)
        {
            ViewBag.User = User.Identity.Name;
            int pageSize = 3; // количество объектов на страницу
            var testsPerPages = DataAcess.TestManagment.GetTestsForPage(page, pageSize);
            var config = new MapperConfiguration(cfg => cfg.CreateMap<DataAcess.DomainModels.Test, IndexTestViewModel>());
            var mapper = config.CreateMapper();
            var tests = mapper.Map<List<DataAcess.DomainModels.Test>, IEnumerable<IndexTestViewModel>>(testsPerPages);
            var pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = DataAcess.TestManagment.GetTestsCount() };
            var ivm = new IndexViewModel { PageInfo = pageInfo, Tests = tests };
            return View(ivm);
        }

        public ActionResult PreStartTest(int testId)
        {
            DataAcess.TestManagment.ClearUserChoice(testId);
            return RedirectToAction("StartTest", new {testId});
        }

        [Authorize]
        public ActionResult StartTest(int testId, int questionId = 1)
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<DataAcess.DomainModels.Question, QuestionViewModel>());
            var mapper = config.CreateMapper();
            var question = mapper.Map<DataAcess.DomainModels.Question, QuestionViewModel>(DataAcess.TestManagment.GetQuestion(testId, questionId));
            var pageInfo = new QuestionPageInfo { TestId = testId, QuestionId = questionId, TotalPages = DataAcess.TestManagment.GetQuestionList(testId).Count};
            var stqvm = new StartTestQuestionViewModel { QuestionPageInfo = pageInfo, Question = question };
            return View(stqvm);
        }

        [HttpPost]
        public ActionResult CheckAnswer(int testId, int questionId)
        {
            var separator = new char[] { ',' };
            var userchoice = Request.Params[questionId.ToString()];
            if (userchoice != null)
            {
                DataAcess.TestManagment.SetUserChoice(testId, questionId, userchoice.Split(separator));
            }
            questionId++;
            if (questionId <= DataAcess.TestManagment.GetQuestionList(testId).Count)
            {
                return RedirectToAction("StartTest", new { testId, questionId });
            }
            else
            {
                return RedirectToAction("TestResult", new { testId });
            }
        }

        [Authorize]
        public ActionResult TestResult(int testId)
        {
            var questions = DataAcess.TestManagment.GetQuestionList(testId);
            TestResultViewModel testResult = new TestResultViewModel
            {
                TestId = testId,
                TestName = DataAcess.TestManagment.GetTest(testId).TestName,
                TotalQuestions = questions.Count
            };


            foreach (var questionid in questions)
            {
                var questionResult = new QuestionResultViewModel { QuestionId = questionid };
                var question = DataAcess.TestManagment.GetQuestion(testId, questionid);
                int userRightAnswered = 0;
                foreach (var option in question.UserChoice)
                {
                    if (!questionResult.UserAnswer.Contains(option))
                    {
                        questionResult.UserAnswer.Add(option);
                    }

                    foreach (var answer in question.RightAnswer)
                    {
                        if (!questionResult.RightAnswer.Contains(answer))
                        {
                            questionResult.RightAnswer.Add(answer);
                        }

                        if (option.ToLower().Contains(answer.ToLower()))
                        {
                            userRightAnswered++;
                        }
                    }
                }

                if (userRightAnswered == question.RightAnswer.Count)
                {
                    testResult.UserRightAnswered++;
                }
                if (question.UserChoice.Count > 0)
                {
                    testResult.UserAnswered++;
                }
                if (DataAcess.TestManagment.GetUser(User.Identity.Name).Role.Contains(DataAcess.DomainModels.Role.Admin))
                {
                    testResult.QuestionInfo.Add(questionResult);
                }

            }
            return View(testResult);
        }

    }
}

KnowledgeTestingApplication/KnowledgeTestingApplication/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using KnowledgeTestingApplication.Models;

namespace KnowledgeTestingApplication.Controllers
{
    public class UserController : Controller
    {
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<DataAcess.DomainModels.User, User>());
            var mapper = config.CreateMapper();
            
            UserIndexViewModel usersViewModel = new UserIndexViewModel();
            var userlist = DataAcess.TestManagment.GetUsersList();
            foreach (var userlogin in userlist)
            {
                var user = mapper.Map<User>(DataAcess.TestManagment.GetUser(userlogin));
                usersViewModel.Users.Add(user);
            }
            return View(usersViewModel);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult EditUser(int id, string login)
        {
            var editUserViewModel = new EditUserModel();
            var config = new MapperConfiguration(cfg => cfg.CreateMap<DataAcess.DomainModels.Role, Role>());
            var mapper = config.CreateMapper();
            editUserViewModel.Id = id;
            editUserViewModel.Email = login;
            editUserViewModel.Role = mapper.Map<List<DataAcess.DomainModels.Role>, List<Role>>(DataAcess.TestManagment.GetUserRoles(id));
            return View(editUserViewModel);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult EditUser(EditUserModel model)
        {
            return RedirectToAction("Index");
        }

        
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteUser(int id, string login)
        {
            var user = DataAcess.TestManagment.GetUser(login);
            var config = new MapperConfiguration(cfg => cfg.CreateMap<DataAcess.DomainModels.User, User>());
            var mapper = config.CreateMapper();

            return View(mapper.Map<User>(user)); 
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteUser(int id)
        {
            DataAcess.TestManagment.DeleteUser(id);
            return RedirectToAction("Index");
        }
    }
}

KnowledgeTestingApplication/KnowledgeTestingApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.User – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    @if (User.Identity.IsAuthenticated)
                     {
                         <span class="icon-bar"></span>
                     }
                </button>
                @Html.ActionLink("Testing App", "Index", "Test", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Test", "Index", "Test")</li>
                    <li>@Html.ActionLink("User control", "Index", "User")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                    @if (User.Identity.IsAuthenticated)
                     {
                            <li>@Html.ActionLink(User.Identity.Name + " Log out", "Logoff", "Account")</li>
                     }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>